server:
  port: 8000
  tomcat:
    uri-encoding: utf-8

spring:
  application:
    name: service-consumer

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: service-consumer
    prefer-ip-address: true

#swagger
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs

info:
  app.name: service-consumer
  company.name: www.zhjd.com
  build.artifactId: com.zhjd
  build.version: 1.0