server:
  port: 8002
  tomcat:
    uri-encoding: utf-8

logging:
  level:
    com.zhjd: DEBUG
    tk.mybatis: ERROR
    org.springframework: ERROR
  file: logs/service-provider-02-log.log
  
mybatis:
  type-aliases-package: com.zhjd.entities                   # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml       # mapper映射文件
  configuration:
    cache-enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000                     #10秒未响应则熔断服务,降级

spring:
   application:
    name: service-provider
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01?serverTimezone=GMT%2B8              # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
      
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: service-provider-02
    prefer-ip-address: true     #访问路径可以显示IP地址     

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

info:
  app.name: service-provider-02
  company.name: www.zhjd.com
  build.artifactId: com.zhjd
  build.version: 1.0
